execute:
  freeze: auto
project:
  resources:
    - "Resources"
    - "style_site.scss"
  type: website
  output-dir: public
website:
  title: "A static jupyter's book website"
  description: "SVD and autoencoder"
  navbar:
    left: 
      - href: Autoencoder.qmd
        text: Autoencoder
      - href: SVD.qmd
        text: SVD
    right:
      - href: https://alexandredabyseesaram.github.io/
        text: Alexandre Daby-Seesaram's homepage
format:
  pdf: default
  html:
    theme:
      light: [flatly, style_site.scss]
      dark: darkly
    css: styles.css
    toc: true



