on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Install Python and ipywidgets
      # - name: Set up Python and install dependencies
      #   uses: actions/setup-python@v4
        # with:
        #   python-version: '3.12'  
      - name: Install jupyter and ipywidgets
        run: |
          pip install jupyter
          pip install ipywidgets

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}